name: container test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name : run test action
          uses: MartinWitt/infer-train@master
