name: container test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name : run test action
          uses: docker://ghcr.io/martinwitt/infer-train@dev
          